version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules # Use a named volume
    command: npm run start

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: npm run dev -- --port 3000 --host # Corrected to 'npm run dev'

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  server_node_modules: # Define the named volume
  client_node_modules: # Define the named volume